### ISSUE TITLE
Is this needed - "remove lookup of string data in hidapi/libusb"?

### ISSUE THREAD

**Issue by karelbilek** [jpochyla/trezord-go#2]
We needed to add this in order for Linux bridge not to hang back in september 2015, in order to fix Linux hangs

https://github.com/trezor/trezord/commit/11ad983464d493800a260f2c86ab6cbb350b3cec

I am not sure if this is an issue of libusb/hidapi, or if it is an issue with libopencm3. (https://github.com/libopencm3/libopencm3/issues/668 maybe? I vaguely remember that being relevant to some bridge and extension bugs, but maybe not this one) 

And I am not sure how to fix that (other than editing the file in `vendor/`)

**Comment by jpochyla** [comment]
Yup it's needed, let's figure out the best way to do it.

**Comment by karelbilek** [comment]
OK done

https://github.com/trezor/usbhid/commit/ddfd675b040c02104a638c8996f8de08a5301ea4
+
https://github.com/jpochyla/trezord-go/pull/23

**Comment by jpochyla** [comment]
Thanks!
